<?php
/**
 * Plugin Name: Corehash Hardening
 * Description: Managed by the Corehash Agent. Do not edit this file; change the settings in your Corehash dashboard.
 * Version:     1.0
 * Author:      Corehash
 *
 * Dit bestand wordt door de agent naar wp-content/mu-plugins gekopieerd
 * zodra er een maatregel wordt aangezet. Welke maatregelen actief zijn
 * staat in de optie corehash_fixes, niet in dit bestand: zo hoeft er
 * nooit code gegenereerd te worden.
 */

if (!defined('ABSPATH')) exit;

$corehash_fixes = (array) get_option('corehash_fixes', []);

/* XML-RPC uit: stopt pingback-misbruik en een veelgebruikte brute-force route */
if (!empty($corehash_fixes['disable_xmlrpc'])) {
    add_filter('xmlrpc_enabled', '__return_false');
    add_filter('wp_headers', function ($headers) {
        unset($headers['X-Pingback']);

        return $headers;
    });
}

/* Gebruikersnamen niet meer publiek opvraagbaar */
if (!empty($corehash_fixes['hide_rest_users'])) {
    add_filter('rest_endpoints', function ($endpoints) {
        if (is_user_logged_in()) return $endpoints;

        foreach (array_keys($endpoints) as $route) {
            if (str_starts_with($route, '/wp/v2/users')) unset($endpoints[$route]);
        }

        return $endpoints;
    });

    add_filter('rest_pre_dispatch', function ($result, $server, $request) {
        if (!is_user_logged_in() && str_starts_with($request->get_route(), '/wp/v2/users')) {
            return new WP_Error('rest_no_route', 'No route was found matching the URL and request method.', ['status' => 404]);
        }

        return $result;
    }, 10, 3);

    add_action('init', function () {
        if (!is_admin() && isset($_GET['author']) && !is_user_logged_in()) {
            wp_redirect(home_url(), 301);
            exit;
        }
    });

    add_filter('oembed_response_data', function ($data) {
        unset($data['author_name'], $data['author_url']);

        return $data;
    });
}

/* Bestandsbewerker in wp-admin op slot */
if (!empty($corehash_fixes['disallow_file_edit']) && !defined('DISALLOW_FILE_EDIT')) {
    define('DISALLOW_FILE_EDIT', true);
}

/* Beveiligingsheaders meesturen */
if (!empty($corehash_fixes['security_headers'])) {
    add_action('send_headers', function () {
        if (is_ssl()) header('Strict-Transport-Security: max-age=31536000');

        header('X-Content-Type-Options: nosniff');
        header('X-Frame-Options: SAMEORIGIN');
        header('Referrer-Policy: strict-origin-when-cross-origin');
    });
}
